# Generated by Django 2.1.8 on 2020-04-30 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premioapp', '0004_auto_20200429_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_routes', to='premioapp.Base')),
            ],
            options={
                'verbose_name': 'Route',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RouteDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Route Day',
                'db_table': 'route_day',
            },
        ),
        migrations.RemoveField(
            model_name='market',
            name='base',
        ),
        migrations.AddField(
            model_name='route',
            name='route_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_day_routes', to='premioapp.RouteDay'),
        ),
        migrations.AddField(
            model_name='market',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='route_markets', to='premioapp.Route'),
            preserve_default=False,
        ),
    ]
