# Generated by Django 3.0.6 on 2020-05-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premioapp', '0005_auto_20200430_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('base', 'name', 'route_day')},
        ),
    ]
