# Generated by Django 2.1.8 on 2020-05-14 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('premioapp', '0003_livelocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='market_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
