# Generated by Django 2.1.8 on 2020-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premioapp', '0004_market_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='propritor_name',
            field=models.CharField(max_length=100),
        ),
    ]
