# Generated by Django 2.1.8 on 2020-10-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premioapp', '0005_auto_20200723_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='market_category', to='premioapp.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=23, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='lng',
            field=models.DecimalField(decimal_places=6, default=90, max_digits=9),
            preserve_default=False,
        ),
    ]
